# Generated by Django 5.2.14 on 2026-05-21 17:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_info", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Proje Adı")),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "language",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Programlama Dili"
                    ),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True, max_length=255, verbose_name="GitHub URL"
                    ),
                ),
                ("stars", models.IntegerField(default=0, verbose_name="Yıldız")),
                ("forks", models.IntegerField(default=0, verbose_name="Fork")),
                ("order", models.IntegerField(default=0, verbose_name="Sıra")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
            ],
            options={
                "verbose_name": "Proje",
                "verbose_name_plural": "Projeler",
                "ordering": ["order", "name"],
            },
        ),
    ]
