# Generated by Django 5.2.14 on 2026-06-04 15:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_info", "0002_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ad Soyad")),
                ("email", models.EmailField(max_length=254, verbose_name="E-posta")),
                ("subject", models.CharField(max_length=200, verbose_name="Konu")),
                ("message", models.TextField(verbose_name="Mesaj")),
                ("is_read", models.BooleanField(default=False, verbose_name="Okundu")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Gönderilme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "İletişim Mesajı",
                "verbose_name_plural": "İletişim Mesajları",
                "ordering": ["-created_at"],
            },
        ),
    ]
